packages:
  - apps/*
  - agents
  - tools/*
  - packages/*

catalog:
  '@tailwindcss/postcss': ^4.1.17
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  clsx: ^2.1.1
  lucide-react: ^0.555.0
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
