packages:
  - apps/*
  - agents
  - tools/*
  - packages/*

catalog:
  '@tailwindcss/postcss': 4.1.17
  '@types/node': 24.10.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@vitest/coverage-v8': ^4.0.14
  clsx: ^2.1.1
  lucide-react: ^0.555.0
  next: ^16.0.6
  next-themes: ^0.4.6
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: 5.9.3
  vitest: 4.0.14
